version: "3.9"
services:
  shared:
    image: "busybox"
    volumes:
      - db:/var/lib/mysql
      - bundle:/usr/local/bundle:cached
      - redis-data:/data:cached
      - "node_modules:/app/node_modules"
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes_from:
      - shared
  redis:
    image: redis
    networks:
      - default
    ports:
      - 6379:6379
    volumes_from:
      - shared
    command: >
      bash -c "mkdir -p /var/log/redis &&
      touch /var/log/redis/redis.log &&
      redis-server --logfile /var/log/redis/redis.log"
    env_file: .env.dev
    volumes:
      - ./api/log:/var/log/redis

  api: &api_base
    build:
      context: ./api
      dockerfile: Dockerfile
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
      bundle exec rails s -p 3001 -b '0.0.0.0'"
    env_file:
      - .env.dev
    volumes:
      - ./api:/app:cached
    volumes_from:
      - shared
    ports:
      - 3001:3001
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    restart: always
  sidekiq:
    <<: *api_base
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    ports: []
    volumes_from:
      - shared
volumes:
  db:
    driver: local
  bundle:
    driver: local
  redis-data:
    driver: local
  node_modules:
    driver: local
