---
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - critical
  - default
  - low
:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:concurrency:   pool: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 } %>
sidekiq_options retry: 5
