inherit_from: .rubocop_todo.yml

require: # .github/workflows/test.yml のrubocop_extensionsと一致させる
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rake
  - rubocop-performance
  - rubocop-rubycw
  - rubocop-i18n
AllCops:
# 対象外
  Exclude:
    - "vendor/**/*"
    - "bin/**"
    - "db/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "lib/**/*"
    - "app/channels/**/*"
    - "config/environments/*"
    - "config/puma.rb"
    - "Gemfile"
  DisplayCopNames: true
  TargetRubyVersion: 3.1.2
  NewCops: enable

# trueかfalseを設定しないと警告が出る
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

##################### Style ##################################

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# ドキュメントの無いpublic classを許可する
Style/Documentation:
  Enabled: false

# !! のイディオムを許可
Style/DoubleNegation:
  Enabled: false

#文字列をfreezeするか
Style/FrozenStringLiteralComment:
  Enabled: false

# selfが無くても良い時に省略するか。model内において、ローカル変数とメソッド呼び出しの区別をつけた方が分かりやすい場合が多い
Style/RedundantSelf:
  Enabled: false

# 文字列リテラルのクォートフォーマットを無効化
Style/StringLiterals:
  Enabled: false

# Hashの配列を[]に強制
Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets
# Wordsの配列を[]に強制
Style/WordArray:
  EnforcedStyle: brackets

# クラスの形式をParentClass::ChildClass形式でコンパクトに記述する
Style/ClassAndModuleChildren:
  EnforcedStyle: nested

# RSpecのワード規約を無効化
ContextWording:
  Enabled: false

##################### Lint ##################################

##################### Metrics ##################################

# 変数の代入(A)、メソッドの呼び出し等(B)、条件分岐(C)から算出される複雑度
Metrics/AbcSize:
  Max: 30

# 循環的複雑度 ≒ 分岐の数
Metrics/CyclomaticComplexity:
  Max: 10

# 1行の文字数
Layout/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

# メソッドの行数
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

# ブロックの長さ（テストファイルだけは除外）
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - "config/routes.rb"
